#!/usr/bin/env python3
"""
Word Document to Markdown Converter

Converts Microsoft Word (.docx) files to Markdown format,
extracting structural elements, formatting, images, and tables.

Usage:
    python docx_to_md.py input.docx output.md [--images-dir images/]
"""

import argparse
import os
import re
import sys
import yaml
from pathlib import Path
from typing import List, Dict, Any, Optional, Tuple
from dataclasses import dataclass, field

from docx import Document
from docx.document import Document as DocumentType
from docx.table import Table
from docx.text.paragraph import Paragraph
from docx.text.run import Run
from docx.oxml.ns import qn
from docx.shared import Pt


# Monospace fonts used to detect code blocks
MONOSPACE_FONTS = {
    'consolas', 'courier', 'courier new', 'lucida console', 
    'monaco', 'menlo', 'dejavu sans mono', 'source code pro',
    'fira code', 'jetbrains mono', 'roboto mono', 'ubuntu mono'
}

# Content to skip (generated by md_to_docx title pages, TOC, etc.)
SKIP_CONTENT_PATTERNS = [
    r'^Table of Contents$',
    r"^Right-click and select 'Update Field'",
    r'^Reviewed and Approved By$',
    r'^_{10,}$',  # Signature lines
]


@dataclass
class ParsedElement:
    """Represents a parsed document element."""
    type: str  # 'heading', 'paragraph', 'table', 'list', 'code_block', 'image', 'horizontal_rule', 'page_break', 'toc'
    content: Any = None
    level: int = 0  # For headings and list indentation
    list_type: str = ''  # 'bullet' or 'numbered'
    items: List[Any] = field(default_factory=list)


class DocxParser:
    """Parse Word document content into structured elements."""
    
    def __init__(self, document: DocumentType, images_dir: str = 'images', 
                 skip_title_page: bool = True, skip_toc: bool = True):
        self.document = document
        self.images_dir = images_dir
        self.skip_title_page = skip_title_page
        self.skip_toc = skip_toc
        self.elements: List[ParsedElement] = []
        self.image_counter = 0
        self.extracted_images: Dict[str, str] = {}  # rId -> filename
        self.front_matter: Dict[str, Any] = {}
        self._in_title_page = True  # Track if we're in title page section
        self._passed_toc = False  # Track if we've passed TOC
        self._toc_placeholder_added = False  # Track if TOC placeholder was added
        
    def parse(self) -> List[ParsedElement]:
        """Parse the document into a list of structured elements."""
        # Extract document properties as front matter
        self._extract_front_matter()
        
        # Extract images first so we can reference them
        self._extract_all_images()
        
        # Process document body
        body = self.document._body._body
        
        # Track list state for grouping
        current_list: Optional[ParsedElement] = None
        current_list_type: Optional[str] = None
        
        # Track code block state for grouping consecutive monospace paragraphs
        code_block_lines: List[str] = []
        
        # Track approval section to skip
        in_approval_section = False
        
        for element in body:
            tag = element.tag.split('}')[-1]  # Remove namespace
            
            if tag == 'p':  # Paragraph
                para = Paragraph(element, self.document._body)
                text = para.text.strip()
                
                # Check for page break in this paragraph
                if self._has_page_break(para):
                    # Flush pending items before page break
                    if current_list:
                        self.elements.append(current_list)
                        current_list = None
                        current_list_type = None
                    if code_block_lines:
                        self.elements.append(ParsedElement(
                            type='code_block',
                            content='\n'.join(code_block_lines)
                        ))
                        code_block_lines = []
                    self.elements.append(ParsedElement(type='page_break'))
                    # If paragraph only contains page break, skip further processing
                    if not text:
                        continue
                
                # Skip empty paragraphs that are just spacing
                if not text and not para.runs:
                    continue
                
                # Check for TOC content - add placeholder once then skip
                if self._is_toc_content(para):
                    if not self._toc_placeholder_added:
                        # Add TOC placeholder element
                        self.elements.append(ParsedElement(type='toc'))
                        self._toc_placeholder_added = True
                    continue  # Skip the actual TOC content
                
                # Check if we should skip this content
                if self._should_skip_content(text, para):
                    continue
                
                # Check for approval section start
                if 'Reviewed and Approved By' in text:
                    in_approval_section = True
                    continue
                
                # Skip signature lines in approval section
                if in_approval_section:
                    # End approval section when we hit regular content
                    if self._get_heading_level(para) or (text and not text.startswith('_')):
                        in_approval_section = False
                        # Don't continue - process this element
                    else:
                        continue
                
                # Detect end of title page (first real heading after title)
                heading_level = self._get_heading_level(para)
                if heading_level and heading_level > 1:  # First content heading (not title)
                    self._in_title_page = False
                
                # Check if it's part of a list
                list_info = self._get_list_info(para)
                
                if list_info:
                    # Flush any pending code block
                    if code_block_lines:
                        self.elements.append(ParsedElement(
                            type='code_block',
                            content='\n'.join(code_block_lines)
                        ))
                        code_block_lines = []
                    
                    list_type, level = list_info
                    item_content = self._extract_paragraph_content(para)
                    
                    # Check if continuing same list or starting new
                    if current_list and current_list_type == list_type:
                        current_list.items.append({'text': item_content, 'level': level})
                    else:
                        # Save previous list if exists
                        if current_list:
                            self.elements.append(current_list)
                        
                        # Start new list
                        current_list = ParsedElement(
                            type='list',
                            list_type=list_type,
                            items=[{'text': item_content, 'level': level}]
                        )
                        current_list_type = list_type
                else:
                    # Not a list item - save any pending list
                    if current_list:
                        self.elements.append(current_list)
                        current_list = None
                        current_list_type = None
                    
                    # Check for heading
                    if heading_level:
                        # Flush pending code block
                        if code_block_lines:
                            self.elements.append(ParsedElement(
                                type='code_block',
                                content='\n'.join(code_block_lines)
                            ))
                            code_block_lines = []
                        
                        self.elements.append(ParsedElement(
                            type='heading',
                            content=self._extract_paragraph_content(para),
                            level=heading_level
                        ))
                    # Check for horizontal rule (paragraph with bottom border only)
                    elif self._is_horizontal_rule(para):
                        if code_block_lines:
                            self.elements.append(ParsedElement(
                                type='code_block',
                                content='\n'.join(code_block_lines)
                            ))
                            code_block_lines = []
                        self.elements.append(ParsedElement(type='horizontal_rule'))
                    # Check for code block (monospace font)
                    elif self._is_code_paragraph(para):
                        code_block_lines.append(self._extract_plain_text(para))
                    else:
                        # Flush pending code block
                        if code_block_lines:
                            self.elements.append(ParsedElement(
                                type='code_block',
                                content='\n'.join(code_block_lines)
                            ))
                            code_block_lines = []
                        
                        # Regular paragraph
                        content = self._extract_paragraph_content(para)
                        if content.strip():
                            self.elements.append(ParsedElement(
                                type='paragraph',
                                content=content
                            ))
                        
                        # Check for inline images
                        images = self._extract_paragraph_images(para)
                        for img in images:
                            self.elements.append(img)
            
            elif tag == 'tbl':  # Table
                # Flush pending items
                if current_list:
                    self.elements.append(current_list)
                    current_list = None
                    current_list_type = None
                if code_block_lines:
                    self.elements.append(ParsedElement(
                        type='code_block',
                        content='\n'.join(code_block_lines)
                    ))
                    code_block_lines = []
                
                # Skip tables in approval section
                if in_approval_section:
                    continue
                
                table = Table(element, self.document._body)
                table_data = self._parse_table(table)
                if table_data:
                    self.elements.append(ParsedElement(
                        type='table',
                        content=table_data
                    ))
        
        # Flush any remaining items
        if current_list:
            self.elements.append(current_list)
        if code_block_lines:
            self.elements.append(ParsedElement(
                type='code_block',
                content='\n'.join(code_block_lines)
            ))
        
        return self.elements
    
    def _should_skip_content(self, text: str, para: Paragraph) -> bool:
        """Check if content should be skipped (TOC, title page elements, etc.)."""
        # Check skip patterns
        for pattern in SKIP_CONTENT_PATTERNS:
            if re.match(pattern, text):
                return True
        
        # Skip title page cosmetic elements (but NOT the Title style itself - that's the document title)
        # (only if we haven't hit real content yet)
        if self._in_title_page and self.skip_title_page:
            style_name = para.style.name.lower() if para.style else ''
            # Do NOT skip Title style - we want to capture it as H1
            # Only skip revision lines and other cosmetic elements on title page
            if text.startswith('Revision ') and len(text) < 20:
                return True
        
        return False
    
    def _is_toc_content(self, para: Paragraph) -> bool:
        """Check if paragraph is part of a Table of Contents."""
        # Check for TOC field content in XML
        para_xml = str(para._p.xml)
        if 'TOC' in para_xml and 'instrText' in para_xml:
            return True
        
        # Check for TOC-related styles
        style_name = para.style.name.lower() if para.style else ''
        if 'toc' in style_name:
            return True
        
        # Check for "Table of Contents" heading
        text = para.text.strip()
        if text == 'Table of Contents':
            return True
        
        return False
    
    def _extract_front_matter(self):
        """Extract document properties to YAML front matter."""
        try:
            core_props = self.document.core_properties
            
            # Extract basic properties
            if core_props.title:
                self.front_matter['full_title'] = core_props.title
            if core_props.subject:
                self.front_matter['document_type'] = core_props.subject
            if core_props.revision:
                self.front_matter['revision'] = core_props.revision
            if core_props.author:
                self.front_matter['author'] = core_props.author
                
        except Exception:
            pass  # Document properties not available
    
    def _extract_all_images(self):
        """Extract all images from the document to the images directory."""
        try:
            # Create images directory if needed
            Path(self.images_dir).mkdir(parents=True, exist_ok=True)
            
            # Access document's related parts for images
            for rel in self.document.part.rels.values():
                if "image" in rel.reltype:
                    image_part = rel.target_part
                    
                    # Determine file extension from content type
                    content_type = image_part.content_type
                    ext = self._get_image_extension(content_type)
                    
                    # Generate filename
                    self.image_counter += 1
                    filename = f"image_{self.image_counter:03d}{ext}"
                    filepath = Path(self.images_dir) / filename
                    
                    # Save image
                    with open(filepath, 'wb') as f:
                        f.write(image_part.blob)
                    
                    # Map relationship ID to filename
                    self.extracted_images[rel.rId] = filename
        except Exception as e:
            print(f"Warning: Could not extract images: {e}", file=sys.stderr)
    
    def _get_image_extension(self, content_type: str) -> str:
        """Get file extension from content type."""
        extensions = {
            'image/png': '.png',
            'image/jpeg': '.jpg',
            'image/gif': '.gif',
            'image/bmp': '.bmp',
            'image/tiff': '.tiff',
            'image/x-emf': '.emf',
            'image/x-wmf': '.wmf',
        }
        return extensions.get(content_type, '.png')
    
    def _get_heading_level(self, para: Paragraph) -> Optional[int]:
        """Determine if a paragraph is a heading and return its level."""
        style_name = para.style.name.lower() if para.style else ''
        
        # Skip TOC heading
        if 'toc' in style_name:
            return None
        
        # Check for Title style - maps to H1 (document title)
        # We always capture the Title style, even on title page
        if 'title' in style_name:
            return 1
        
        # Check for Heading styles
        if style_name.startswith('heading'):
            # Extract number from style name (e.g., "Heading 1" -> 1)
            match = re.search(r'heading\s*(\d+)', style_name)
            if match:
                level = int(match.group(1))
                # Shift up by 1 since Title is H1
                return level + 1
        
        return None
    
    def _get_list_info(self, para: Paragraph) -> Optional[Tuple[str, int]]:
        """Check if paragraph is a list item and return (type, level)."""
        # Check for numbering properties in paragraph XML
        pPr = para._p.pPr
        if pPr is None:
            return None
        
        numPr = pPr.find(qn('w:numPr'))
        if numPr is None:
            # Check for manual bullet character at start
            text = para.text.strip()
            if text.startswith('•') or text.startswith('○'):
                return ('bullet', 0)
            return None
        
        # Get indentation level
        ilvl = numPr.find(qn('w:ilvl'))
        level = int(ilvl.get(qn('w:val'))) if ilvl is not None else 0
        
        # Get numbering ID to determine type
        numId = numPr.find(qn('w:numId'))
        if numId is None:
            return None
        
        num_id_val = int(numId.get(qn('w:val')))
        
        # Try to determine if bullet or numbered from numbering definitions
        # For simplicity, we'll check the text pattern
        text = para.text.strip()
        
        # Check if starts with number pattern
        if re.match(r'^\d+[\.\)]\s', text) or re.match(r'^[a-z][\.\)]\s', text, re.IGNORECASE):
            return ('numbered', level)
        
        # Check if starts with bullet
        if text.startswith('•') or text.startswith('○') or text.startswith('-'):
            return ('bullet', level)
        
        # Default: check numId - lower IDs often are bullet, higher numbered
        # This is a heuristic that may not always work
        if num_id_val <= 1:
            return ('numbered', level)
        else:
            return ('bullet', level)
    
    def _is_code_paragraph(self, para: Paragraph) -> bool:
        """Check if a paragraph uses monospace font (likely code)."""
        if not para.runs:
            return False
        
        # Check if all runs use monospace font
        for run in para.runs:
            font_name = self._get_run_font(run)
            if font_name and font_name.lower() in MONOSPACE_FONTS:
                continue
            elif run.text.strip():  # Non-empty run without monospace
                return False
        
        # All non-empty runs are monospace
        return any(run.text.strip() for run in para.runs)
    
    def _is_horizontal_rule(self, para: Paragraph) -> bool:
        """Check if paragraph is a horizontal rule (border-only paragraph)."""
        pPr = para._p.pPr
        if pPr is None:
            return False
        
        pBdr = pPr.find(qn('w:pBdr'))
        if pBdr is None:
            return False
        
        # Check if it has a bottom border and minimal/no text
        bottom = pBdr.find(qn('w:bottom'))
        if bottom is not None and not para.text.strip():
            return True
        
        return False
    
    def _has_page_break(self, para: Paragraph) -> bool:
        """Check if paragraph contains a page break.
        
        Page breaks in Word documents appear as <w:br w:type="page"/> within runs.
        """
        # Look for page break elements within the paragraph
        for br in para._p.findall('.//w:br',
            {'w': 'http://schemas.openxmlformats.org/wordprocessingml/2006/main'}):
            br_type = br.get(qn('w:type'))
            if br_type == 'page':
                return True
        return False
    
    def _get_run_font(self, run: Run) -> Optional[str]:
        """Get the font name from a run."""
        # Try direct font name
        if run.font.name:
            return run.font.name
        
        # Try from run properties XML
        rPr = run._r.rPr
        if rPr is not None:
            rFonts = rPr.find(qn('w:rFonts'))
            if rFonts is not None:
                # Check various font attributes
                for attr in ['w:ascii', 'w:hAnsi', 'w:cs']:
                    font = rFonts.get(qn(attr))
                    if font:
                        return font
        
        return None
    
    def _extract_paragraph_content(self, para: Paragraph) -> str:
        """Extract paragraph content with inline formatting markers.
        
        This method properly handles both regular runs and hyperlinks by iterating
        through the paragraph's child elements in order, ensuring hyperlink text
        is captured and converted to markdown link syntax.
        """
        result = []
        
        # Build a map of relationship IDs to URLs for hyperlinks
        rels = self.document.part.rels
        
        # Iterate through paragraph children in document order
        # This ensures we capture both regular runs and hyperlinks in sequence
        for child in para._p:
            tag = child.tag.split('}')[-1]  # Remove namespace
            
            if tag == 'hyperlink':
                # Handle hyperlink element
                r_id = child.get(qn('r:id'))
                url = None
                
                if r_id and r_id in rels:
                    rel = rels[r_id]
                    url = rel.target_ref
                
                # Also check for anchor (internal bookmark links)
                anchor = child.get(qn('w:anchor'))
                if anchor and not url:
                    url = f"#{anchor}"
                
                # Extract all text from runs within the hyperlink
                link_text_parts = []
                for run_elem in child.findall('.//w:r',
                    {'w': 'http://schemas.openxmlformats.org/wordprocessingml/2006/main'}):
                    # Get text from within the run
                    for t_elem in run_elem.findall('.//w:t',
                        {'w': 'http://schemas.openxmlformats.org/wordprocessingml/2006/main'}):
                        if t_elem.text:
                            link_text_parts.append(t_elem.text)
                
                link_text = ''.join(link_text_parts)
                
                if link_text and url:
                    result.append(f"[{link_text}]({url})")
                elif link_text:
                    # No URL found, just output the text
                    result.append(link_text)
                    
            elif tag == 'r':
                # Handle regular run element
                run = Run(child, para)
                text = run.text
                if not text:
                    continue
                
                # Apply formatting
                font_name = self._get_run_font(run)
                is_monospace = font_name and font_name.lower() in MONOSPACE_FONTS
                
                if run.bold and run.italic:
                    text = f"***{text}***"
                elif run.bold:
                    text = f"**{text}**"
                elif run.italic:
                    text = f"*{text}*"
                elif is_monospace:
                    text = f"`{text}`"
                
                result.append(text)
        
        return ''.join(result)
    
    def _extract_plain_text(self, para: Paragraph) -> str:
        """Extract plain text from paragraph without formatting."""
        return para.text
    
    def _extract_paragraph_images(self, para: Paragraph) -> List[ParsedElement]:
        """Extract images referenced in a paragraph."""
        images = []
        
        # Find drawing elements (inline images)
        drawings = para._p.findall('.//w:drawing', 
                                    {'w': 'http://schemas.openxmlformats.org/wordprocessingml/2006/main'})
        
        for drawing in drawings:
            # Find the blip element which contains the image reference
            blips = drawing.findall('.//{http://schemas.openxmlformats.org/drawingml/2006/main}blip')
            
            for blip in blips:
                embed = blip.get('{http://schemas.openxmlformats.org/officeDocument/2006/relationships}embed')
                if embed and embed in self.extracted_images:
                    filename = self.extracted_images[embed]
                    images.append(ParsedElement(
                        type='image',
                        content=filename
                    ))
        
        return images
    
    def _parse_table(self, table: Table) -> List[List[str]]:
        """Parse a Word table into a 2D list of cell contents with formatting."""
        data = []
        
        for row in table.rows:
            row_data = []
            for cell in row.cells:
                # Extract content with formatting from all paragraphs in cell
                cell_parts = []
                for para in cell.paragraphs:
                    para_content = self._extract_paragraph_content(para)
                    if para_content.strip():
                        cell_parts.append(para_content.strip())
                cell_text = ' '.join(cell_parts)
                row_data.append(cell_text)
            data.append(row_data)
        
        return data


class MarkdownGenerator:
    """Generate Markdown from parsed document elements."""
    
    def __init__(self, elements: List[ParsedElement], images_dir: str = 'images',
                 front_matter: Optional[Dict[str, Any]] = None,
                 preserve_heading_numbers: bool = True):
        self.elements = elements
        self.images_dir = images_dir
        self.front_matter = front_matter or {}
        self.preserve_heading_numbers = preserve_heading_numbers
        
    def generate(self) -> str:
        """Generate markdown content from parsed elements."""
        lines = []
        
        # Add front matter if present
        if self.front_matter:
            lines.append('---')
            # Use yaml.dump but strip the trailing newline
            yaml_content = yaml.dump(self.front_matter, default_flow_style=False, allow_unicode=True)
            lines.append(yaml_content.rstrip())
            lines.append('---')
            lines.append('')
        
        for i, element in enumerate(self.elements):
            # Add blank line before most elements (except first after front matter)
            if lines and lines[-1] != '' and element.type not in ['image']:
                lines.append('')
            
            if element.type == 'heading':
                lines.append(self._heading_to_md(element))
            elif element.type == 'paragraph':
                lines.append(self._paragraph_to_md(element))
            elif element.type == 'table':
                lines.extend(self._table_to_md(element))
            elif element.type == 'list':
                lines.extend(self._list_to_md(element))
            elif element.type == 'code_block':
                lines.extend(self._code_block_to_md(element))
            elif element.type == 'image':
                lines.append(self._image_to_md(element))
            elif element.type == 'horizontal_rule':
                lines.append('---')
            elif element.type == 'page_break':
                lines.append('<!-- pagebreak -->')
            elif element.type == 'toc':
                lines.append('<!-- toc -->')
        
        # Clean up excessive blank lines
        result = '\n'.join(lines)
        result = re.sub(r'\n{3,}', '\n\n', result)
        
        return result.strip() + '\n'
    
    def _heading_to_md(self, element: ParsedElement) -> str:
        """Convert heading to markdown."""
        text = element.content
        
        # Optionally strip auto-generated numbers from heading
        if not self.preserve_heading_numbers:
            text = re.sub(r'^[\d]+[.\d]*\.?\s+', '', text)  # Remove leading numbers
        
        hashes = '#' * element.level
        return f"{hashes} {text}"
    
    def _paragraph_to_md(self, element: ParsedElement) -> str:
        """Convert paragraph to markdown."""
        return element.content
    
    def _table_to_md(self, element: ParsedElement) -> List[str]:
        """Convert table to markdown."""
        if not element.content:
            return []
        
        data = element.content
        lines = []
        
        # Determine column widths for alignment (optional, markdown doesn't require it)
        if not data:
            return []
        
        num_cols = max(len(row) for row in data)
        
        # Generate header row
        if data:
            header = '| ' + ' | '.join(data[0]) + ' |'
            lines.append(header)
            
            # Generate separator row
            separator = '|' + '|'.join(['---'] * num_cols) + '|'
            lines.append(separator)
            
            # Generate data rows
            for row in data[1:]:
                # Pad row if needed
                while len(row) < num_cols:
                    row.append('')
                row_str = '| ' + ' | '.join(row) + ' |'
                lines.append(row_str)
        
        return lines
    
    def _list_to_md(self, element: ParsedElement) -> List[str]:
        """Convert list to markdown."""
        lines = []
        numbered_counters = {}  # Track counters per level
        
        for item in element.items:
            text = item['text']
            level = item.get('level', 0)
            indent = '  ' * level
            
            # Strip any existing bullet/number from text
            text = re.sub(r'^[•○-]\s*', '', text)
            text = re.sub(r'^\d+[\.\)]\s*', '', text)
            text = re.sub(r'^[a-z][\.\)]\s*', '', text, flags=re.IGNORECASE)
            
            if element.list_type == 'numbered':
                # Track numbering per level
                if level not in numbered_counters:
                    numbered_counters[level] = 0
                numbered_counters[level] += 1
                # Reset deeper levels
                for l in list(numbered_counters.keys()):
                    if l > level:
                        del numbered_counters[l]
                
                lines.append(f"{indent}{numbered_counters[level]}. {text}")
            else:
                lines.append(f"{indent}- {text}")
        
        return lines
    
    def _code_block_to_md(self, element: ParsedElement) -> List[str]:
        """Convert code block to markdown."""
        lines = ['```']
        lines.extend(element.content.split('\n'))
        lines.append('```')
        return lines
    
    def _image_to_md(self, element: ParsedElement) -> str:
        """Convert image reference to markdown."""
        filename = element.content
        # Use relative path from markdown file location
        image_path = f"{self.images_dir}/{filename}"
        return f"![{filename}]({image_path})"


class DocxToMarkdownConverter:
    """Main converter class orchestrating the conversion process."""
    
    def __init__(self, images_dir: str = 'images', preserve_heading_numbers: bool = True,
                 skip_title_page: bool = True, skip_toc: bool = True,
                 include_front_matter: bool = False):
        self.images_dir = images_dir
        self.preserve_heading_numbers = preserve_heading_numbers
        self.skip_title_page = skip_title_page
        self.skip_toc = skip_toc
        self.include_front_matter = include_front_matter
        
    def convert(self, input_path: str, output_path: str) -> str:
        """Convert a Word document to Markdown.
        
        Args:
            input_path: Path to input .docx file
            output_path: Path for output .md file
            
        Returns:
            Generated markdown content
        """
        print(f"Reading: {input_path}")
        
        # Load document
        document = Document(input_path)
        
        # Determine images directory relative to output file
        output_dir = Path(output_path).parent
        images_dir = output_dir / self.images_dir
        
        # Parse document
        print("Parsing document structure...")
        parser = DocxParser(document, str(images_dir), 
                           skip_title_page=self.skip_title_page,
                           skip_toc=self.skip_toc)
        elements = parser.parse()
        
        print(f"Found {len(elements)} elements")
        
        # Get front matter if requested
        front_matter = parser.front_matter if self.include_front_matter else {}
        
        # Generate markdown
        print("Generating markdown...")
        generator = MarkdownGenerator(
            elements, 
            self.images_dir,
            front_matter=front_matter,
            preserve_heading_numbers=self.preserve_heading_numbers
        )
        markdown = generator.generate()
        
        # Write output
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(markdown)
        
        print(f"Document saved to: {output_path}")
        
        # Report on images
        if parser.extracted_images:
            print(f"Extracted {len(parser.extracted_images)} images to: {images_dir}")
        
        return markdown


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description='Convert Word Document to Markdown',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog='''
Examples:
    python docx_to_md.py input.docx output.md
    python docx_to_md.py input.docx output.md --images-dir assets/images
    python docx_to_md.py input.docx output.md --preserve-numbers
    python docx_to_md.py input.docx output.md --include-front-matter
        '''
    )
    
    parser.add_argument('input', help='Input Word document (.docx) path')
    parser.add_argument('output', help='Output Markdown file path')
    parser.add_argument(
        '--images-dir', '-i',
        help='Directory for extracted images (relative to output file, default: images)',
        default='images'
    )
    parser.add_argument(
        '--preserve-numbers', '-n',
        action='store_true',
        default=True,
        help='Preserve heading numbers in output (default: True)'
    )
    parser.add_argument(
        '--strip-numbers',
        action='store_true',
        help='Strip auto-generated heading numbers'
    )
    parser.add_argument(
        '--include-title-page',
        action='store_true',
        help='Include title page content in output'
    )
    parser.add_argument(
        '--include-toc',
        action='store_true', 
        help='Include table of contents in output'
    )
    parser.add_argument(
        '--include-front-matter', '-f',
        action='store_true',
        help='Extract document properties as YAML front matter'
    )
    
    args = parser.parse_args()
    
    # Validate input file
    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Error: Input file not found: {args.input}")
        sys.exit(1)
    
    if not input_path.suffix.lower() == '.docx':
        print(f"Warning: Input file may not be a Word document: {args.input}")
    
    # Determine preserve_numbers setting
    preserve_numbers = not args.strip_numbers
    
    # Convert
    converter = DocxToMarkdownConverter(
        images_dir=args.images_dir,
        preserve_heading_numbers=preserve_numbers,
        skip_title_page=not args.include_title_page,
        skip_toc=not args.include_toc,
        include_front_matter=args.include_front_matter
    )
    converter.convert(args.input, args.output)
    
    print("Conversion complete!")


if __name__ == '__main__':
    main()
